server:
  port: 8189
  servlet:
    context-path:

spring:
  datasource:
  url: jdbc:h2:mem:mall_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  username: sa
  password:
  data: classpath:/sql/import-h2.sql